/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
<<<<<<< HEAD
=======
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
<<<<<<< HEAD
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as AuthenticatedSpoudeRouteImport } from './routes/_authenticated/spoude'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
=======
import { Route as ApiTeachRouteImport } from './routes/api/teach'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLumioRouteImport } from './routes/_authenticated/lumio'
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedSetsIdRouteImport } from './routes/_authenticated/sets.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
=======
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
=======
const ApiTeachRoute = ApiTeachRouteImport.update({
  id: '/api/teach',
  path: '/api/teach',
  getParentRoute: () => rootRouteImport,
} as any)
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
<<<<<<< HEAD
const AuthenticatedSpoudeRoute = AuthenticatedSpoudeRouteImport.update({
  id: '/spoude',
  path: '/spoude',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
=======
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
<<<<<<< HEAD
=======
const AuthenticatedLumioRoute = AuthenticatedLumioRouteImport.update({
  id: '/lumio',
  path: '/lumio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetsIdRoute = AuthenticatedSetsIdRouteImport.update({
  id: '/sets/$id',
  path: '/sets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
<<<<<<< HEAD
=======
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/library': typeof AuthenticatedLibraryRoute
<<<<<<< HEAD
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spoude': typeof AuthenticatedSpoudeRoute
  '/study': typeof AuthenticatedStudyRoute
=======
  '/lumio': typeof AuthenticatedLumioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/study': typeof AuthenticatedStudyRoute
  '/api/teach': typeof ApiTeachRoute
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
  '/sets/$id': typeof AuthenticatedSetsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
<<<<<<< HEAD
=======
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/library': typeof AuthenticatedLibraryRoute
<<<<<<< HEAD
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spoude': typeof AuthenticatedSpoudeRoute
  '/study': typeof AuthenticatedStudyRoute
=======
  '/lumio': typeof AuthenticatedLumioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/study': typeof AuthenticatedStudyRoute
  '/api/teach': typeof ApiTeachRoute
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
  '/sets/$id': typeof AuthenticatedSetsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
<<<<<<< HEAD
=======
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
  '/terms': typeof TermsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
<<<<<<< HEAD
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/spoude': typeof AuthenticatedSpoudeRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
=======
  '/_authenticated/lumio': typeof AuthenticatedLumioRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/api/teach': typeof ApiTeachRoute
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
  '/_authenticated/sets/$id': typeof AuthenticatedSetsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
<<<<<<< HEAD
=======
    | '/reset-password'
    | '/sitemap.xml'
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
    | '/terms'
    | '/billing'
    | '/exams'
    | '/library'
<<<<<<< HEAD
    | '/profile'
    | '/settings'
    | '/spoude'
    | '/study'
=======
    | '/lumio'
    | '/profile'
    | '/settings'
    | '/study'
    | '/api/teach'
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
    | '/sets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
<<<<<<< HEAD
=======
    | '/reset-password'
    | '/sitemap.xml'
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
    | '/terms'
    | '/billing'
    | '/exams'
    | '/library'
<<<<<<< HEAD
    | '/profile'
    | '/settings'
    | '/spoude'
    | '/study'
=======
    | '/lumio'
    | '/profile'
    | '/settings'
    | '/study'
    | '/api/teach'
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
    | '/sets/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
<<<<<<< HEAD
=======
    | '/reset-password'
    | '/sitemap.xml'
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
    | '/terms'
    | '/_authenticated/billing'
    | '/_authenticated/exams'
    | '/_authenticated/library'
<<<<<<< HEAD
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/spoude'
    | '/_authenticated/study'
=======
    | '/_authenticated/lumio'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/study'
    | '/api/teach'
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
    | '/_authenticated/sets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
<<<<<<< HEAD
  TermsRoute: typeof TermsRoute
=======
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiTeachRoute: typeof ApiTeachRoute
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
=======
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
=======
    '/api/teach': {
      id: '/api/teach'
      path: '/api/teach'
      fullPath: '/api/teach'
      preLoaderRoute: typeof ApiTeachRouteImport
      parentRoute: typeof rootRouteImport
    }
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
<<<<<<< HEAD
    '/_authenticated/spoude': {
      id: '/_authenticated/spoude'
      path: '/spoude'
      fullPath: '/spoude'
      preLoaderRoute: typeof AuthenticatedSpoudeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
=======
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
<<<<<<< HEAD
=======
    '/_authenticated/lumio': {
      id: '/_authenticated/lumio'
      path: '/lumio'
      fullPath: '/lumio'
      preLoaderRoute: typeof AuthenticatedLumioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sets/$id': {
      id: '/_authenticated/sets/$id'
      path: '/sets/$id'
      fullPath: '/sets/$id'
      preLoaderRoute: typeof AuthenticatedSetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
<<<<<<< HEAD
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSpoudeRoute: typeof AuthenticatedSpoudeRoute
=======
  AuthenticatedLumioRoute: typeof AuthenticatedLumioRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
  AuthenticatedSetsIdRoute: typeof AuthenticatedSetsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
<<<<<<< HEAD
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSpoudeRoute: AuthenticatedSpoudeRoute,
=======
  AuthenticatedLumioRoute: AuthenticatedLumioRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
  AuthenticatedSetsIdRoute: AuthenticatedSetsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
<<<<<<< HEAD
  TermsRoute: TermsRoute,
=======
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiTeachRoute: ApiTeachRoute,
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
<<<<<<< HEAD
=======

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
>>>>>>> 6eb08cd852ad86633840258078184b8cf02d3132
